blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("<int:id>/", views.blog_detail, name="blog_detail"),
    path("tag/<slug:tag>/", views.blog_tag, name="tag"),
    path("category/<slug:category>/", views.blog_category, name="category"),
    path("search/", views.search, name="search"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls', namespace='foods')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foods/urls.py
from django.urls import path
from . import views


app_name = "foods"
urlpatterns = [
    path("", views.food_list, name="food_names"),
    path("<int:id>/", views.food_detail, name="detail"),
]

reservation/urls.py
from django.urls import path
from . import views


app_name = "reservation"
urlpatterns = [
    path("", views.reserve, name='reserve'),
]

templates/partials/_footer.html
<footer style="font-family:'Shabnam'" class="footer-area bg-f">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <h3>درباره ی ما</h3>
                <p>.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است </p>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3>ساعت های باز</h3>
                <p><span class="text-color">دوشنبه: </span>بسته</p>
                <p><span class="text-color">سه شنبه-چهارشنبه :</span> ۹ صبح تا ۱۰ شب</p>
                <p><span class="text-color">پنجشنبه-جمعه :</span> ۹ صبح تا ۱۰ شب</p>
                <p><span class="text-color">شنبه-یکشنبه :</span> ۵ عصر تا ۱۰ شب</p>
            </div>
            <div class="col-lg-4 col-md-6">
                <h3>اطلاعات تماس</h3>
                <p class="lead">تهران، شهران شمالی</p>
                <p class="lead"><a href="#">۰۹۰۳۷۰۸۹۷۹۴</a></p>
                <p><a href="#"> amingit2022@gmail.com</a></p>
            </div>
        </div>
    </div>
    
</footer>

templates/partials/_header.html
<header style="font-family:'Shabnam'" class="top-navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="index.html">
                <img src="images/logo.png" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-rs-food">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active ml-2"><a class="nav-link" href="{% url 'foods:food_names' %}">خانه</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ml-2" href="#" id="dropdown-a" data-toggle="dropdown">صفحه ها</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            <a class="dropdown-item" href="{% url 'reservation:reserve' %}">رزرو</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown ml-2">
                        <a class="nav-link" href="{% url 'blog:blog_list' %}" id="dropdown-a">بلاگ</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>