blog/urls.py
from django.urls import path
from . import views


app_name = "blog"
urlpatterns = [
    path("", views.blog_list, name="blog_list"),
    path("<int:id>/", views.blog_detail, name="blog_detail"),
    path("tag/<slug:tag>/", views.blog_tag, name="tag"),
    path("category/<slug:category>/", views.blog_category, name="category"),
    path("search/", views.search, name="search"),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls', namespace='foods')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Blog(models.Model):
    """This model is related to post creation."""

    title = models.CharField(_("عنوان"),max_length=50)
    description = models.CharField(_("توضیحات"),max_length=100)
    content = RichTextField(_("متن"))
    created_at = models.DateTimeField(_("زمان انتشار"), default=timezone.now)
    author = models.ForeignKey(User, verbose_name=_("نویسنده"), on_delete=models.CASCADE)
    image = models.ImageField(_("تصویر"), upload_to="blogs/")
    category = models.ForeignKey("Category", related_name="blog", verbose_name=_("دسته بندی"), on_delete=models.CASCADE)
    tags = models.ManyToManyField("Tag", verbose_name=_("تگ ها"), related_name="blogs")

    def __str__(self):
        return self.title



class Category(models.Model):
    """This model is related to the category of posts."""

    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title



class Tag(models.Model):
    """This model is related to post tags."""

    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    update_at = models.DateTimeField(_("تاریخ بروزرسانی"), auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    


class Comment(models.Model):
    """This model is related to posting comments on posts."""

    blog = models.ForeignKey("Blog", verbose_name=_("مقاله"), related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(_("نام کاربر"), max_length=100)
    email = models.EmailField(_("ایمیل"), max_length=254)
    message = models.TextField(_("متن نظر"))
    date = models.DateField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    """This form is related to posting comments on posts."""
    
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, required=True)
    message = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Blog, Tag, Category, Comment
from django.db.models import Q
from .forms import CommentForm


def blog_list(request):
    """This view is related to the listing of posts."""

    blogs = Blog.objects.all()
    context={
        "blogs":blogs
    }
    return render(request, "blog/blog_list.html", context)



def blog_detail(request, id):
    """
    This view is related to the details of the posts, where 
    there are categories, tags, comments and recent posts.
    """

    blog = get_object_or_404(Blog, id=id)
    tags = Tag.objects.filter(blogs=blog)
    recents = Blog.objects.order_by("-created_at")[:4]
    categories = Category.objects.all()
    comments = Comment.objects.filter(blog=blog)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data["name"]
            new_email = form.cleaned_data["email"]
            new_message = form.cleaned_data["message"]
            
            new_comment = Comment(blog=blog, name=new_name, email=new_email, message=new_message)
            new_comment.save()

    context={
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
        "comments":comments
    }
    return render(request, "blog/blog_detail.html", context)



def blog_tag(request, tag):
    """This view is related to our posts tag."""

    blogs = Blog.objects.filter(tags__slug=tag)
    context={
        "blogs":blogs
    }
    return render(request, "blog/blog_list.html", context) 



def blog_category(request, category):
    """This view is related to the category of our posts."""

    blogs = Blog.objects.filter(category__slug=category)
    context={
        "blogs":blogs
    }
    return render(request, "blog/blog_list.html", context) 



def search(request):
    """This view is related to searching on the details page of our posts."""

    if request.method == "GET":
        q = request.GET.get("search")
    blogs = Blog.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
    context={
        "blogs":blogs
    }

    return render(request, "blog/blog_list.html", context) 

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<div style="font-family:'Shabnam'">
		<!-- Start All Pages -->
		<div class="all-page-title page-breadcrumb">
			<div class="container text-center">
				<div class="row">
					<div class="col-lg-12">
						<h1 style="font-family:'Shabnam'">بلاگ</h1>
					</div>
				</div>
			</div>
		</div>
		<!-- End All Pages -->
		
		<!-- Start blog details -->
		<div class="blog-box">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="heading-title text-center">
							<h2 style="font-family:'Shabnam'">تیتر: {{ blog.title }}</h2>
							<p>توضیحات: {{ blog.description }}</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xl-8 col-lg-8 col-12">
						<div class="blog-inner-details-page">
							<div class="blog-inner-box">
								<div class="side-blog-img">
									<img class="img-fluid" src="{{ blog.image.url }}" alt="">							
									<div class="date-blog-up">
										{{ blog.created_at | date:"Y b d" }}
									</div>
								</div>
								<div class="inner-blog-detail details-page">
									<h3>{{ blog.description }}</h3>
									<ul>
										<li><span>نوشته شده توسط {{ blog.author }}</span></li>
										<li>|</li>
										<li><span>{{ blog.created_at|date:"Y b d" }}</span></li>
									</ul>
									<p dir="rtl">{{ blog.content | safe }}</p>
								</div>
							</div>
							<div class="blog-comment-box">
								<h3>نظرات</h3>
								{% for cm in comments %}
									<div class="comment-item">
										<div class="comment-item-left">
											<img src="images/avt-img.jpg" alt="">
										</div>
										<div class="comment-item-right">
											<div class="pull-left">
												<i class="fa fa-clock-o" aria-hidden="true"></i>Date : <span>{{ cm.date }}</span>
											</div>
											<div class="pull-right">
												<a href="#">{{ cm.name }}</a>
											</div>
											<div class="des-l">
												<p align="right">{{ cm.message }}</p>
											</div>
										</div>
									</div>
								{% endfor %}
								
							</div>
							<div class="comment-respond-box">
								<h3>نظر بگذارید </h3>
								<div class="comment-respond-form">
									<form id="commentrespondform" class="comment-form-respond row" method="post">
										{% csrf_token %}
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="form-group">
												<input id="name_com" class="form-control" name="name" placeholder="نام" type="text">
											</div>
											<div class="form-group">
												<input id="email_com" class="form-control" name="email" placeholder="ایمیل" type="email">
											</div>
										</div>
										<div class="col-lg-6 col-md-6 col-sm-6">
											<div class="form-group">
												<textarea class="form-control" name="message" id="textarea_com" placeholder="پیام شما" rows="2"></textarea>
											</div>
										</div>
										<div class="col-lg-12 col-md-12 col-sm-12">
											<button class="btn btn-submit">ارسال نظر</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				
					<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
						<div class="right-side-blog">
							<h3>جستجو</h3>
							<form method="GET" action="{% url 'blog:search' %}">
								<div class="blog-search-form">
									<input name="search" placeholder="جستجوی بلاگ" type="text">
									<button class="search-btn" type="submit">
										<i class="fa fa-search" aria-hidden="true"></i>
									</button>
								</div>
							</form>
							<h3 class="ml-5">دسته بندی ها</h3>
							<div class="blog-categories ml-5">
								<ul>
									{% for cat in categories %}
										<li><a href="{% url 'blog:category' cat.slug %}"><span>{{ cat.title }}</span></a></li>
									{% endfor %}
								</ul>
							</div>
							<h3 class="ml-5">پست های جدید</h3>
							<div class="post-box-blog ml-5">
								<div class="recent-post-box">
									{% for blog in recents %}
										<div class="recent-box-blog">
											<div class="recent-img">
												<img class="img-fluid" style="width:70px; height:70px" src="{{ blog.image.url }}" alt="">
											</div>
											<div class="recent-info">
												<ul>
													<li><i class="zmdi zmdi-account"></i>نوشته شده توسط: <span>{{ blog.author.first_name }}</span></li>
													<li>|</li>
													<li><i class="zmdi zmdi-time"></i>زمان: <span>{{ blog.created_at|time}}</span></li>
												</ul>
												<h4>{{ blog.description }}</h4>
											</div>
										</div>
									{% endfor %}
								</div>
							</div>
							<h3 class="ml-5">تگ های جدید</h3>
							<div class="blog-tag-box ml-5">
								<ul class="list-inline tag-list">
									{% for tag in tags %}
										<li class="list-inline-item"><a href="{% url 'blog:tag' tag.slug %}">{{ tag.title }}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				
				</div>
			</div>
		</div>
		<!-- End details -->
		
		<!-- Start Contact info -->
		<div class="contact-imfo-box">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<i class="fa fa-volume-control-phone"></i>
						<div class="overflow-hidden">
							<h4>تلفن</h4>
							<p class="lead">
								۰۹۰۳۷۰۸۹۷۹۴
							</p>
						</div>
					</div>
					<div class="col-md-4">
						<i class="fa fa-envelope"></i>
						<div class="overflow-hidden">
							<h4>ایمیل</h4>
							<p class="lead">
								amingit2022@gmail.com
							</p>
						</div>
					</div>
					<div class="col-md-4">
						<i class="fa fa-map-marker"></i>
						<div class="overflow-hidden">
							<h4>آدرس</h4>
							<p class="lead">
								شهران، شهران شمالی
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Contact info -->
	</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<div style="font-family:'Shabnam'">
		<!-- Start All Pages -->
			<div class="all-page-title page-breadcrumb">
				<div class="container text-center">
					<div class="row">
						<div class="col-lg-12">
							<h1 style="font-family:'Shabnam'">بلاگ</h1>
						</div>
					</div>
				</div>
			</div>
		<!-- End All Pages -->
			
		<!-- Start blog -->
			<div class="blog-box">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="heading-title text-center">
								<h2 style="font-family:'Shabnam'">لیست پست ها</h2>
							</div>
						</div>
					</div>
					<div class="row">
						{% for blog in blogs %}
							<div class="col-lg-4 col-md-6 col-12">
								<div class="blog-box-inner">
									<div class="blog-img-box">
										<img class="img-fluid" src="{{ blog.image.url }}" style="height:530px" alt="image">
									</div>
									<div class="blog-detail">
										<h4>{{ blog.title }}</h4>
										<ul>
											<li><span>نوشته شده توسط {{ blog.author }}</span></li>
											<li>|</li>
											<li><span>{{ blog.created_at|date:"Y b d" }}</span></li>
										</ul>
										<p dir="rtl">{{ blog.content|safe|truncatewords:80 }}</p>
										<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blog_detail' blog.id %}">ادامه ی مطلب</a>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		<!-- End blog -->

		
		<!-- Start Contact info -->
			<div class="contact-imfo-box">
				<div class="container">
					<div class="row">
						<div class="col-md-4">
							<i class="fa fa-volume-control-phone"></i>
							<div class="overflow-hidden">
								<h4>تلفن</h4>
								<p class="lead">
									۰۹۰۳۷۰۸۹۷۹۴
								</p>
							</div>
						</div>
						<div class="col-md-4">
							<i class="fa fa-envelope"></i>
							<div class="overflow-hidden">
								<h4>ایمیل</h4>
								<p class="lead">
									amingit2022@gmail.com
								</p>
							</div>
						</div>
						<div class="col-md-4">
							<i class="fa fa-map-marker"></i>
							<div class="overflow-hidden">
								<h4>آدرس</h4>
								<p class="lead">
									تهران، شهران شمالی
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Contact info -->
	</div>
{% endblock %}